server:
  port: 9001
  tomcat:
    max-connections: 10000
  compression:
    enabled: true
    min-response-size: 0KB
    mime-types: application/json
  max-http-header-size: 10MB

spring:
  application:
    name: spring-cloud-upms
  #  profiles:
  #    active: dev
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  #      config:
  #        server-addr: 127.0.0.1:8848
  #        file-extension: yml
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/spring-cloud-upms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: true
      pool-name: UpmsHikariCP
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  configuration:
    local-cache-scope: statement
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

logging:
  level:
    com.github.samples: info
  file:
    name: ${spring.application.name}.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'